services: 
  bento:
    image: lewisdoesstuff/bento-next
    volumes:
      # Append Bento config/.env location to below line.
      - /config.ts:/usr/share/nginx/html/config.ts
      - /.env:/usr/share/nginx/html/.env
    ports:
      # Replace host port 80 (left side) with desired port.
      - 1234:8080